adding AWS - database backup/restore
shaal/DrupalPod pull request #18
Opened 2021-07-12 02:25 UTC by shaal

# The Problem/Issue/Bug
It's not possible to maintain consistent database across workspaces.

## How this PR Solves The Problem
Add AWS commands:
`.gitpod/aws/aws-backup.sh [backup_name]`
`.gitpod/aws/aws-restore.sh [backup_name]`

## Manual Testing Instructions
1. Create new Gitpod Environment variables through CLI (or directly in https://gitpod.io/variables)
`gp env AWS_ACCESS_KEY_ID=[ID]`
`gp env AWS_SECRET_ACCESS_KEY=[SECRET]`
`gp env AWS_DEFAULT_BUCKET=[BUCKET_NAME]
1. open a new workspace (or stop/start current workspace, for `gp env` to take effect)
1. Make some changes in current website.
1. Run `aws-backup.sh testing123` (for a named backup)
1. Make additional changes in current website.
1. Run `aws-backup.sh` (for general backup, to be used later in Gitpod's future end-tasks)
1. Close workspace
1. Open a new workspace
1. Run `aws-restore.sh testing123` (for restoring the named backup)
1. Confirm first changes are in the website, after its DB was restored.
1. Run `aws-restore.sh` (for restoring the latest backup available)
1. Confirm second changes are in the website, after its DB was restored.

## Related Issue Link(s)

## Release/Deployment notes

2021-07-12 03:48 UTC, rfay requested changes
Please add docs (or prompting?) equivalent to the PR manual testing instructions. I went straight to the PR expecting to see instructions there.

2021-07-12 20:31 UTC, mikenikles commented
Elegant - the first word that came to mind 😄.

I'd love for this to be part of the new Gitpod Guides section we're working on (https://github.com/gitpod-io/website/issues/709) 🎉.

2021-07-13 23:11 UTC, rfay commented
One interesting thought would be to add a docker volume plugin like https://github.com/muthu-r/horcrux - that would allow saving and restoring snapshots directly from S3 or minio. I haven't tried it. And that plugin doesn't look active.

2021-07-16 18:51 UTC, bioshazard approved these changes

2024-09-17 15:52 UTC, closed without merging